### ISSUE TITLE
Feature request: Add port as output to `upstash_kafka_cluster`

### ISSUE THREAD

**Issue by benkraus** [upstash/terraform-provider-upstash#10]
`upstash_kafka_cluster`'s `tcp_endpoint` does not include the port, and thus when attempting to configure a Lambda integration for a consumer, it fails - I had to add and hardcode the port manually. Would be nice to get that as an output so no hardcoding would be required.

**Comment by burak-upstash** [comment]
Hi again, @benkraus!

Default port for the kafka clusters is 9092. What I mean is, the port does not change like in the case of our redis databases. 

We may release a version for this in the future. In the mean time, you can keep that port info in a variable instead in order not to hardcode everytime.
