### ISSUE TITLE
Feature request: Add `topic_name` as an output to `upstash_kafka_topic`

### ISSUE THREAD

**Issue by benkraus** [upstash/terraform-provider-upstash#11]
When configuring a Lambda consumer to a given topic, the consumer and topics were declared in separate Terraform modules, thus a `local` not useful for reusability. Would be nice to reference an imported topic's name instead of hard coding the name of the topic to match where it was defined.

**Comment by burak-upstash** [comment]
Hi there @benkraus !

Could you elaborate on what you mean by importing the topic's name? 
You should be able to give the topic name already as an output. From there, you can use terraform's configuration docs to see how to import between modules.

For reference: https://stackoverflow.com/questions/47034515/terraform-output-a-field-from-a-module

I hope that helps!

**Comment by burak-upstash** [comment]
For the last 30 days, no response was given. For that, closing the issue.
