### ISSUE TITLE
Manage Kafka credentials

### ISSUE THREAD

**Issue by petecracknell-immo** [upstash/terraform-provider-upstash#14]
It would be great if we could manage Kafka credentials in Terraform. Matching behaviour in https://developer.upstash.com/#create-kafka-credential

**Comment by burak-upstash** [comment]
Hey @petecracknell-immo, we have implemented Kafka Credential resource to our Terraform provider. Just update your version and you should be good to go! 
(There are examples on how to use the resource in /examples folder, you can take reference from there. )
