### ISSUE TITLE
Kafka topic docs clarity

### ISSUE THREAD

**Issue by petecracknell-immo** [upstash/terraform-provider-upstash#16]
Hi

For the [Kafka Topic documentation](https://github.com/upstash/terraform-provider-upstash/blob/master/docs/resources/kafka_topic.md), could you please specify the units for both time and size.

**Comment by petecracknell-immo** [comment]
Also, how do I set the retention and message size policies to infinite? I suggest these be documented in the page too.

**Comment by burak-upstash** [comment]
For the sizes, unit is `byte` and for time, unit is `millisecond-ms`. For the infinite values, you can give -1 as the value. However, if it is not permitted -regarding your payment plan-, you will have created with the max value available to you - 1 TB for instance- .

Thank you for bringing this to our attention! We will add that info soon.

**Comment by burak-upstash** [comment]
We have added the unit info to our developer api. Closing for now.
