### ISSUE TITLE
What's the output of a redis_database?

### ISSUE THREAD

**Issue by StarpTech** [upstash/terraform-provider-upstash#3]
Hi, as titled. I'd like to get access to the database URL, port and token.

**Comment by burak-upstash** [comment]
Hi there! Current version of the provider provides the endpoint, which can be converted to the URL by prefixing `https://<endpoint>` .
For the port and the rest tokens, we expect to release a new version soon.

**Comment by buggyhunter** [comment]
https://registry.terraform.io/providers/upstash/upstash/1.0.2 has been released with a fix. now all credentials can be received as terraform output
closing the issue for now
