### ISSUE TITLE
Migrate Go from 1.16 to 1.21

### ISSUE THREAD

**Issue by khareyash05** [upstash/terraform-provider-upstash#33]
I would like to help migrate Go from 1.16 to 1.21 as it has reached of end of life. Reference - [https://endoflife.date/go](https://endoflife.date/go)

**Comment by buggyhunter** [comment]
Hello @khareyash05 , please, you can definitely help us. Can you prepare a PR?

**Comment by khareyash05** [comment]
What minimum version should I chose for the go.mod file? 1.21?

**Comment by khareyash05** [comment]
@buggyhunter Created a PR . Kindly review
