### ISSUE TITLE
Does not work with mac m1

### ISSUE THREAD

**Issue by paulrostorp** [upstash/terraform-provider-upstash#4]
Upon adding the provider and running `terraform init`, I get:
```
Error: Incompatible provider version
Provider registry.terraform.io/upstash/upstash v1.0.0 does not have a package available for your current platform, darwin_arm64.
```

**Comment by fdionisi** [comment]
I'm experiencing the same issue.

As far as I can tell, the Upstash provider is built with Go v1.14. However, the GoReleaser documentation [^1] states that support for Apple Silicon via `darwin/arm64` starts from Go v1.16.

I'm not a Go lang developer, and I never build a provider, so I may be wrong here. But if that's the case, I'm happy to open a PR. I looked around, and from an M1 supported provider [^2], the only necessary change seems to be a language version bump.

[^1]: https://goreleaser.com/deprecations/#builds-for-darwinarm64
[^2]: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/.github/workflows/release.yml#L16-L20

**Comment by buggyhunter** [comment]
@paulrostorp @fdionisi we are working on this issue as high-prio issue
Thanks for reporting

**Comment by chronark** [comment]
@paulrostorp @fdionisi v1.0.1 works
