### ISSUE TITLE
Expose Redis database port

### ISSUE THREAD

**Issue by fdionisi** [upstash/terraform-provider-upstash#6]
I noticed that each Redis database listens on a different port, and at the moment, that's not exposed by the Terraform resource. This behaviour makes it nearly impossible to deploy and have a resource connecting to the newly created database in one go (unless you guess and hardcode the port, and you are extremely lucky 😅).

Looking at Upstash API [^1], the port is provided in the response payload when creating a new database, so this feature request should be trivial to implement.

Here's the error message I receive when trying to access the `port` attribute:
```
╷
│ Error: Unsupported attribute
│ 
│   on main.tf line 396, in resource "aws_lambda_function" "api_lambda":
│  396:       HIVE_REDIS_URL = "rediss://:${upstash_redis_database.cache.password}@${upstash_redis_database.cache.endpoint}:${upstash_redis_database.cache.port}"
│ 
│ This object has no argument, nested block, or exported attribute named "port".
╵
```

[^1]: https://developer.upstash.com/#create-database

**Comment by buggyhunter** [comment]
@fdionisi yes you are right.. rest endpoint should work but we will add port for tcp endpoints. expecting another fix/release today.

**Comment by fdionisi** [comment]
Amazing @buggyhunter! Thank you for taking the time.

FYI, the journey with Upstash has been great so far and your prompt reactions are levelling up the experience even more. 😁

**Comment by burak-upstash** [comment]
Hey, thanks for the issue! We will be checking if any other info similar to those are missing with the provider.

**Comment by buggyhunter** [comment]
https://registry.terraform.io/providers/upstash/upstash/1.0.2 has been released with a fix
closing the issue for now
